### ISSUE TITLE
Allow language word ('w') lookup by gloss item

### ISSUE THREAD

**Issue by olzama** [goodmami/xigt#15]
Currently, if I want to use word-level alignment in Gloss and Language lines, it seems necessary to iterate through morpheme tier in a case like kor-ex.xml. I.e., I first need to find all the morphemes that correspond to a word, then all the gloss items that correspond to these morphemes. It would be convenient to be able to look up a word-level gloss item by word item id, and vice versa.

**Comment by goodmami** [comment]
Thanks for requesting this. But to clarify, do you want to get a list of gloss items from a word, or a list of words from a gloss? Both should be possible. I'm working on a good interface for this. Perhaps something like:

```python
>>> list(ancestors(gloss_item, refattrs=('alignment', 'segmentation')))
(<Tier object (id: m type: morphemes) at ...>, 'alignment', [<Item object (id: m1) at ... >])
(<Tier object (id: w type: words) at ...>, 'segmentation', [<Item object (id: w1) at ... >])
(<Tier object (id: p type: phrases) at ...>, 'segmentation', [<Item object (id: p1) at ... >])
```

That is, you give it an item (like a gloss) and a list of reference attributes it can follow (first match in the list; ('alignment', 'segmentation') is the default list), and it will traverse the references. It returns a triple of `(tier, refattr, [items])` where `tier` is the referred tier, `refattr` is the reference attribute it followed to get there, and `[items]` is a list of items referred by the items in the previous level (usually this is only 1, but for converging structures (like syntax trees) you'll get multiple).

In order to find the level you want, just iterate and stop at the desired type:

```python
>>> for (reftier, refattr, items) in ancestors(gloss_item):
...    if reftier.type == 'words':
...        print('found {} matching word(s)'.format(len(items)))
found 1 matching word(s)
```

Going the other way, I can have a `descendants()` function similarly defined, but you're more likely to get more than one result. When this happens, each matching tier has all collected results (e.g. you might get 2 morpheme descendants for a word, and 2 gloss descendants for each morpheme, so the result of morphemes has an items list with 4 items. This should be fine as long as the list of refattrs is mutually exclusive (e.g. a tier can refer to another by alignment or by segmentation, not by both).

Does such a proposal seem like it would work for you?

**Comment by olzama** [comment]
Thanks for looking into this!

Yes, it sounds like the descendants() function is exactly what I am looking for. Right now in my user scenario, I start from words in the sentence (which originally come from a Xigt document's words tier), and I need to find the items in the glosses tier that correspond to this word. So I end up iterating through the morphemes first, finding all that have this word as their alignment attribute, then find all the glosses that have these morphemes as their alignment attribute, etc. Having a function that would retrieve all the glosses for me, given a word id, would be very convenient. In fact, am I right to iterate through morphemes in the first place? Maybe there is already a function which would give me the morphemes that correspond to a word? It is possible that I didn't find something.

But, basically, my scenario is: given a word, find things that are aligned to it in other tiers.

**Comment by goodmami** [comment]
Since alignments go "upward", it is easy to find, e.g., what words align to which morphs, but there is no reverse index for the other direction. Maybe I should consider that as well..

**Comment by goodmami** [comment]
Both ancestors() and descendants() are implemented in a feature branch. The difference from what I wrote before is that they yield 4-tuples: (sourcetier, refattr, reftier, refitems). The sourcetier is the new part, and it was necessary particularly for descendants() since more than one tier can refer to another with the same reference attribute, unlike for ancestors().
