### ISSUE TITLE
Metadata uses "text" for iterables?

### ISSUE THREAD

**Issue by rgeorgi** [goodmami/xigt#16]
Whereas "text" is used elsewhere for the text nodes, the Metadata class appears to use "text" for its children; this seems inconsistent.

**Comment by goodmami** [comment]
Yes, that is inappropriate. I think I will require all <metadata> elements to have <meta> children, so I can make it use "metas" for getting children. Either way, "text" is the wrong thing to call it.

**Comment by goodmami** [comment]
This should be resolved by a32c295127758c260c5a4cb2e82702ae52abb7e8 (actually before, but this commit is the first one that isn't broken I think).

While Metadata.text is renamed to Metadata.metas, you can still use .text (but you'll get a DeprecationWarning) in case any code relies on it. Also, I still have Meta.text even though some examples (like the [OLAC example](https://github.com/goodmami/xigt/blob/master/examples/odin/kor-ex-olac.xml)) have nested XML, and I've stated in the paper that deeper XML structure is possible under <meta>. I'm not certain what to do here, yet, since without a schema or fixed format, I don't know how to parse the deeper structure into a Python representation. Some options:

1. Parse into a pseudo-JSON-like dictionary
2. Re-serialize anything under <meta> to text and just store it in the text attribute
3. Have special parsers for non-text <meta> content (e.g. a special one for OLAC)
